server:
  #访问HTTP端口号
  port: 8086
  servlet:
    context-path: "/hystrix-dashborad"


########################################################
### 指定日志文件
########################################################
logging:
  config: classpath:log4j2.xml


#########################################################
#### Spring配置
#########################################################
spring:

  ################################################## Spring Cloud Alibaba 配置 ##########################################
  cloud:
    nacos:
      discovery:
        enabled: true #如果不想使用Nacos进行服务注册与发现,设置为false即可
        server-addr: 139.196.155.56:8848,139.196.155.56:8858 #服务注册地址
        namespace: 53dc28d0-21c8-46fd-be52-b206940b7f0d #命名空间ID
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator


  application:
    name: hystrix-dashborad #服务名


  thymeleaf:
    check-template: false
    check-template-location: false

################################################### Spring Boot Actuator 配置 ##########################################
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  #需要开放的端点,默认只打开health 和 info 两个端点.通过设置 * ,可以开放所有端点
  endpoint:
    health:
      show-details: always #健康检查是否显示详细信息


#########################################################
#### Hystrix 熔断、降级配置
#########################################################
hystrix:
  dashboard:
    #允许被哪个IP地址打开（可添加多个）
    proxy-stream-allow-list: 127.0.0.1