########################################################
###datasource
########################################################
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.103.64.174
    # Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: Gm859230
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
  datasource:
    druid:
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.103.64.174:3306/fz_seal_type_select?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: Gm859230
        initialSize: 2
        minIdle: 2
        maxActive: 5
        validationQuery: SELECT 1 from dual
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        maxWait: 6000
        filters: wall,stat,slf4j
      quartz:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.103.64.174:3306/db_quartz?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: Gm859230
        initialSize: 2
        minIdle: 2
        maxActive: 5
        validationQuery: SELECT 1 from dual
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        maxWait: 6000
        filters: wall,stat,slf4j
    tomcat:
      #最大连接池数量
      max-active: 20
      #最小连接池数量
      min-idle: 8
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法,或者第一次getConnection时
      initial-size: 10
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    #注册中心客户端名称
    name: seal-type-select
  cloud:
    nacos:
      discovery:
        #配置注册中心服务端地址
        server-addr: 101.132.126.135:8848
    sentinel:
      transport:
        #跟控制台交流的端口,随意指定一个未使用的端口即可
        port: 8719
        #指定sentinel 控制台服务地址
        dashboard: 101.132.126.135:8858
      filter:
        #关闭sentinel的CommonFilter实例化
        enabled: false




########################################################
### Ribbon 负载均衡策略配置
########################################################
### 针对单个服务的 Ribbon 配置
fuzhao-industry:
  ribbon:
    #ribbon的超时时间
    ReadTimeout: 60000
    ConnectTimeout: 60000
    # 随机 负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


########################################################
### feign 配置
########################################################
feign:
  sentinel:
    #开启feign对sentinel的支持
    enabled: true

########################################################
###Quartz 配置
########################################################
quartz:
  scheduler-name: seal-type-select